spring.application.name=HealthAssistBackend


# Spring AI: Azure OpenAI API key for authenticating requests to Azure OpenAI service
spring.ai.azure.openai.api-key=${AZURE_OPENAI_KEY}

# Spring AI: Azure OpenAI endpoint URL for accessing the LLM service
spring.ai.azure.openai.endpoint=${AZURE_OPENAI_ENDPOINT}

# Spring AI: Specifies which Azure OpenAI deployment/model to use for chat completions
spring.ai.azure.openai.chat.options.deployment-name=${DEPLOYMENT_NAME}

logging.level.org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor=DEBUG

spring.ai.azure.openai.chat.options.temperature=1